# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07267a2a5e89ab4afc75207d9e4737f4b8598ec59b85181d2d4bcf75feb05dae00fb2bdd93cc97e466d854da744c3b8330964cd474f6d16070ed5028ac26f5b7

test:
  secret_key_base: 25cd6c85b925c4ffa0b13e7c7394996157cd6192cf9fe2d3a32aa7d53122f684cd493fc98c6a8cfd3664a2842f197880af836c268e003b29212ec33e678cf1c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
